"""Test helpers for creating deterministic game setups."""

from __future__ import annotations

import random
from typing import Sequence

from bang_game_engine.cards.card import Card
from bang_game_engine.cards.card_color import CardColor
from bang_game_engine.cards.card_face import CardFace
from bang_game_engine.cards.deck import Deck
from bang_game_engine.cards.rank import Rank
from bang_game_engine.cards.suit import Suit
from bang_game_engine.effects.effect_stack import EffectStack
from bang_game_engine.effects.registry import EffectRegistry
from bang_game_engine.expansions.base.expansion import BaseGameExpansion
from bang_game_engine.game.game_state import GameState
from bang_game_engine.game.state_machine import GameStateMachine
from bang_game_engine.game.turn_rules import TurnRuleEngine
from bang_game_engine.game.win_condition import WinConditionEvaluator
from bang_game_engine.players.character import Character
from bang_game_engine.players.distance_service import DistanceService
from bang_game_engine.players.player import Player
from bang_game_engine.players.role import Role
from bang_game_engine.players.seating import Seating
from bang_game_engine.shared.identifiers import new_card_id, new_game_id, new_player_id
from bang_game_engine.shared.types import PlayerId


def make_card(
    card_type: str = "bang",
    suit: Suit = Suit.HEARTS,
    rank: Rank = Rank.ACE,
    color: CardColor = CardColor.BROWN,
) -> Card:
    return Card(
        id=new_card_id(),
        card_type=card_type,
        face=CardFace(suit=suit, rank=rank),
        color=color,
    )


def make_character(name: str = "test_char", base_hp: int = 4, abilities=None) -> Character:
    return Character(
        character_type=name,
        name=name.replace("_", " ").title(),
        base_hp=base_hp,
        abilities=abilities or [],
    )


def setup_game(
    roles: list[Role],
    characters: list[Character] | None = None,
    deck_cards: list[Card] | None = None,
) -> tuple[GameStateMachine, list[PlayerId]]:
    """
    Create a fully controlled game setup.
    Returns (machine, [player_ids]) where player_ids[0] is the Sheriff.
    """
    n = len(roles)
    if characters is None:
        characters = [make_character(f"char_{i}") for i in range(n)]

    players: dict[PlayerId, Player] = {}
    pids: list[PlayerId] = []
    sheriff_id = None

    for i in range(n):
        pid = new_player_id()
        players[pid] = Player(
            player_id=pid,
            role=roles[i],
            character=characters[i],
        )
        pids.append(pid)
        if roles[i] == Role.SHERIFF:
            sheriff_id = pid

    # Put sheriff first
    if sheriff_id and pids[0] != sheriff_id:
        idx = pids.index(sheriff_id)
        pids[0], pids[idx] = pids[idx], pids[0]

    seating = Seating(pids)

    if deck_cards is None:
        # Create a large deck of assorted cards
        deck_cards = []
        for _ in range(20):
            deck_cards.append(make_card("bang"))
        for _ in range(15):
            deck_cards.append(make_card("missed"))
        for _ in range(10):
            deck_cards.append(make_card("beer"))
        for _ in range(5):
            deck_cards.append(make_card("stagecoach"))
        random.shuffle(deck_cards)

    deck = Deck(draw_pile=deck_cards, rng=random.Random(42))

    base = BaseGameExpansion()
    effect_registry = EffectRegistry()
    base.register_effects(effect_registry)
    turn_rule_engine = TurnRuleEngine()
    base.register_turn_rules(turn_rule_engine)

    game_state = GameState(
        game_id=new_game_id(),
        players=players,
        seating=seating,
        deck=deck,
        effect_stack=EffectStack(),
        effect_registry=effect_registry,
        turn_rule_engine=turn_rule_engine,
        win_evaluator=WinConditionEvaluator(),
        distance_service=DistanceService(),
    )

    machine = GameStateMachine(game_state)
    return machine, pids


def give_card_to_player(
    machine: GameStateMachine, player_id: PlayerId, card: Card
) -> None:
    """Directly add a card to a player's hand (for test setup)."""
    machine.game_state.get_player(player_id).add_to_hand(card)
    # Flush events generated by add_to_hand
    machine.game_state.collect_events()


def skip_to_next_turn(machine: GameStateMachine, player_id: PlayerId) -> None:
    """End the current player's turn, discarding down to hand limit as needed."""
    from bang_game_engine.game.commands import DiscardCardCommand, EndPhaseCommand
    from bang_game_engine.game.phase import Phase

    machine.handle_command(EndPhaseCommand(player_id=player_id))
    player = machine.game_state.get_player(player_id)
    while (
        machine.active_player_id == player_id
        and machine.current_phase == Phase.DISCARD_PHASE
    ):
        card = player.hand[0]
        machine.handle_command(
            DiscardCardCommand(player_id=player_id, card_id=card.id)
        )
