from bang_game_engine.card.card import (
    Card,
    CardSuits,
    CardTypes,
    CardValues,
    GunCard,
    ModifierCard,
)
from bang_game_engine.deck.deck import Deck
from bang_game_engine.deck.interfaces import IDeck, IDeckFactory


class BangDeckFactory(IDeckFactory):
    def create(self) -> IDeck:
        deck: list[Card] = [
            GunCard(
                suit=CardSuits.CLUB,
                value=CardValues.TEN,
                card_type=CardTypes.VOLCANIC,
                distance_range=1,
            ),
            GunCard(
                suit=CardSuits.SPADE,
                value=CardValues.TEN,
                card_type=CardTypes.VOLCANIC,
                distance_range=1,
            ),
            GunCard(
                suit=CardSuits.CLUB,
                value=CardValues.JACK,
                card_type=CardTypes.SCHOFIELD,
                distance_range=2,
            ),
            GunCard(
                suit=CardSuits.CLUB,
                value=CardValues.QUEEN,
                card_type=CardTypes.SCHOFIELD,
                distance_range=2,
            ),
            ModifierCard(
                suit=CardSuits.HEART,
                value=CardValues.NINE,
                card_type=CardTypes.MUSTANG,
            ),
            ModifierCard(
                suit=CardSuits.HEART,
                value=CardValues.EIGHT,
                card_type=CardTypes.MUSTANG,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.BANG,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.BANG,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.BANG,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.BANG,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.BANG,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.MISSED,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.MISSED,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.MISSED,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.MISSED,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.MISSED,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.MISSED,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.GENERAL_STORE,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.GENERAL_STORE,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.GATLING,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.SALOON,
            ),
            Card(
                suit=CardSuits.HEART,
                value=CardValues.TWO,
                card_type=CardTypes.WELLS_FARGO,
            ),
        ]

        return Deck(deck)
